-- Biar connect ke database nya di cmd ketik:
-- npx prisma db push

-- add user
-- http://localhost:5000/register
-- {
--   "name": "admin",
--   "email": "admin@gmail.com",
--   "username": "admin",
--   "password": "admin",
--   "role": "ADMIN"
-- }
